name: Release fizzbuzz for the world

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Run tests
        run: go test -v -cover

      - name: Compile
        run: go build -o 